// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdutyvtvnyeqxnkonomg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkdXR5dnR2bnllcXhua29ub21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDcwMzEsImV4cCI6MjA2NTMyMzAzMX0.xSNxpWMptyfuORKFwRMY-wbvmsHuAvje0KsRhQiVStQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);